### ISSUE TITLE
Add search engine in API page

### ISSUE THREAD

**Issue by JesusValera** [phel-lang/phel-lang.org#8]
## 📚  Description

The idea is to be able to find symbols in `API`, right now it's a mess.

## ⚠️ Dependencies

In order to be able to work on this feature, the https://github.com/phel-lang/phel-lang.org/pull/5 should be merged.

![image](https://user-images.githubusercontent.com/6381924/122746277-26034380-d28a-11eb-964d-6aa0e2cc435c.png)

**Comment by Chemaclass** [comment]
I think we need to start thinking about redesign the website because we want to add another section for tutorials and learning purposes, not simply docu 🤔 

And yes, this searching functionality is something really interesting that we need to start thinking about. This is the official docu from Zola: https://www.getzola.org/documentation/content/search/

**Comment by JesusValera** [comment]
We need to implement the search in the mobile version, but I think we can close this issue for now.
